version: "3.7"
services:
    db:
        image: postgres
        container_name: api-pgsql
        restart: unless-stopped
        user: postgres
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data
            - ./docker-compose/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
        networks:
            - php-api
    db-testing:
        image: postgres
        container_name: api-pgsql-testing
        restart: unless-stopped
        user: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: testing
        ports:
            - "5433:5433"
        volumes:
            - postgres:/var/lib/postgresql/data
            - ./docker-compose/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
        networks:
            - php-api
    
networks:
    php-api:
        driver: bridge
volumes:
    postgres:
